#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="settings.example.json" --destination="$install_dir/settings.json"

#=================================================
# HANDLE LOG FILES AND LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Documentation tool for creativity" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL DODOC
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
 	ynh_hide_warnings ynh_exec_as_app npm install
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Server up and running"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
